### ISSUE TITLE
VOR 07L Not working

### ISSUE THREAD

**Issue by GivenPaladin809** [Epse/betty#34]
![Screenshot 2024-08-11 212025](https://github.com/user-attachments/assets/969e2a90-6d7b-4691-852c-c0b1555ab15a)

When generating a 07s scenario, aircraft appear to be spawning on a 25L final and then doing some sort of back course VOR for 07L, which makes it very weird and hard to manage for a mentor.

**Comment by Epse** [comment]
Noted, the spawn point appears to be off, as well as the approach definition being oddly formatted. That second one should also have been an issue with the previous script / bot approach.
