### ISSUE TITLE
Scenario Generator/ Multiple issues

### ISSUE THREAD

**Issue by GivenPaladin809** [Epse/betty#36]
[scenario_EBBR-2519DEP25RARR-HIGH.txt](https://github.com/user-attachments/files/16905605/scenario_EBBR-2519DEP25RARR-HIGH.txt)

In this scenario file, there were two major issues related to generator:
ITY149 spawning at GA apron instead of Apron 1 (check image below)
![Screenshot 2024-09-04 192028](https://github.com/user-attachments/assets/6e738883-83c2-433b-881a-6bfd66d320d5)

Aircraft with destination EHAM actually spawning with destination HELE

**Comment by Epse** [comment]
Point 1:
- Aircraft types BCS1 and BCS3 are defined as private jets in the gate manager dataset. Will follow up there

**Comment by Epse** [comment]
And for point two, you wouldn't happen to know _which_ aircraft that is and why you assume it's heading to EHAM?

**Comment by Epse** [comment]
Point two is fixed.
